version: '3.1'

services:
  app:
    container_name: app
    image: 'springboot-crud-app'
    build:
      context: .
    ports:
      - "8080:8080"
    depends_on:
      - postgresqldb
    environment:
      - server.port=8080
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgresqldb:5432/postgres
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update

  postgresqldb:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=123456